name: insta_clone
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_storage: ^11.2.6
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  flutter_svg: ^2.0.5
  cloud_firestore: ^4.3.1
  image_picker: ^1.0.2
  flutter_dotenv: ^5.1.0
  provider: ^6.0.5
  uuid: ^4.0.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  flutter_staggered_grid_view: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/.env
    - assets/images/
#    - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

