// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkmaIeeCvzq31qPXRebWW8SsItwTvsOEI',
    appId: '1:1051891993189:web:9c7216be6214a28dba548c',
    messagingSenderId: '1051891993189',
    projectId: 'clone-project-yasir',
    authDomain: 'clone-project-yasir.firebaseapp.com',
    storageBucket: 'clone-project-yasir.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwR4RndsUP1wQKmXoqer9UngpNTIbKrQg',
    appId: '1:1051891993189:android:071cc8188e9e3a58ba548c',
    messagingSenderId: '1051891993189',
    projectId: 'clone-project-yasir',
    storageBucket: 'clone-project-yasir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJzn7VPe-KR-tpNQ0z5mnjeJtdNeixcHo',
    appId: '1:1051891993189:ios:bbcbf0603520830dba548c',
    messagingSenderId: '1051891993189',
    projectId: 'clone-project-yasir',
    storageBucket: 'clone-project-yasir.appspot.com',
    androidClientId: '1051891993189-oshlkrsobumq5iabedd9bp66bpr587io.apps.googleusercontent.com',
    iosClientId: '1051891993189-48tevnmdvg8ruiq107n3oh4becf4mmnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJzn7VPe-KR-tpNQ0z5mnjeJtdNeixcHo',
    appId: '1:1051891993189:ios:bbcbf0603520830dba548c',
    messagingSenderId: '1051891993189',
    projectId: 'clone-project-yasir',
    storageBucket: 'clone-project-yasir.appspot.com',
    androidClientId: '1051891993189-oshlkrsobumq5iabedd9bp66bpr587io.apps.googleusercontent.com',
    iosClientId: '1051891993189-48tevnmdvg8ruiq107n3oh4becf4mmnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
